-- MySQL Script generated by MySQL Workbench
-- Sun Oct 27 01:33:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`parent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parent` (
  `reg_num` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `occupation` VARCHAR(45) NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reg_num`),
  UNIQUE INDEX `reg_num_UNIQUE` (`reg_num` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sem_one`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sem_one` (
  `reg_no` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `chemistry` INT NOT NULL,
  `physics` INT NOT NULL,
  `maths` INT NOT NULL,
  PRIMARY KEY (`reg_no`),
  UNIQUE INDEX `reg_no_UNIQUE` (`reg_no` ASC) VISIBLE,
  UNIQUE INDEX `chemistry_UNIQUE` (`chemistry` ASC) VISIBLE,
  UNIQUE INDEX `physics_UNIQUE` (`physics` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sem_two`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sem_two` (
  `reg_no` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `electronics` INT NOT NULL,
  `electrical` INT NOT NULL,
  `civil_mech` INT NOT NULL,
  PRIMARY KEY (`reg_no`),
  UNIQUE INDEX `reg_no_UNIQUE` (`reg_no` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activity_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`activity_points` (
  `reg_no` INT NOT NULL,
  `name_student` VARCHAR(45) NOT NULL,
  `matter` VARCHAR(45) NOT NULL,
  `point` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reg_no`),
  UNIQUE INDEX `reg_no_UNIQUE` (`reg_no` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `reg_num` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fathers_name` VARCHAR(45) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`reg_num`),
  UNIQUE INDEX `reg_num_UNIQUE` (`reg_num` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `reg_parent`
    FOREIGN KEY (`reg_num`)
    REFERENCES `mydb`.`parent` (`reg_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reg_one`
    FOREIGN KEY (`reg_num`)
    REFERENCES `mydb`.`sem_one` (`reg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reg_two`
    FOREIGN KEY (`reg_num`)
    REFERENCES `mydb`.`sem_two` (`reg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reg_ap`
    FOREIGN KEY (`reg_num`)
    REFERENCES `mydb`.`activity_points` (`reg_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `teacher_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacher_id`),
  UNIQUE INDEX `teacher_id_UNIQUE` (`teacher_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
